var fs=require("fs");
var out=[];
out.push(fs.readFileSync(__dirname+'/../skyjs/js/overload.js', 'utf-8'));
out.push(fs.readFileSync(__dirname+'/../skyjs/js/core.js', 'utf-8'));
out.push(fs.readFileSync(__dirname+'/../skyjs/js/extend.js', 'utf-8'));
out.push(fs.readFileSync(__dirname+'/../skyjs/js/promise.js', 'utf-8'));
out.push(fs.readFileSync(__dirname+'/../url-polyfill/URL.js', 'utf-8'));
out.push(fs.readFileSync(__dirname+'/../skyjs/js/script.js', 'utf-8'));
out.push(fs.readFileSync(__dirname+'/loader.js', 'utf-8'));
fs.writeFileSync(__dirname+'/sky-loader.js', out.join("\n"), 'utf-8');
var bundle=require("./bundle");
bundle(__dirname+"/animal","/animal");